### ISSUE TITLE
Group goals

### ISSUE THREAD

**Issue by ScottWales** [ACDguide/BigData#2]
Add the group goals from google docs to the website

**Comment by paigem** [comment]
I'd be happy to do this. @ScottWales would this be something we add to the jupyter book? I.e. should I convert it into markdown or notebook format, or just upload as a pdf? (Apologies - haven't used jupyter book before so I don't know how this all works!)

**Comment by ScottWales** [comment]
Sure, thanks. Probably best to add it as markdown rather than pdf, that way it should show up nicer on the webpage. Add the markdown file to the 'BigData' directory, then add the filename without extension to `_toc.yml`. The table of contents will read the top-level section name from the file, it doesn't need to match the filename.

**Comment by paigem** [comment]
Thanks for the help Scott!

Closing with [this](https://github.com/ACDguide/BigData/pull/3#issue-672202923) pull request.

**Comment by paigem** [comment]
Oops - looks like I can't close issues. @ScottWales want to close this issue?

**Comment by ScottWales** [comment]
Permissions should hopefully be updated now
