### ISSUE TITLE
Tools page: different_tools needs work

### ISSUE THREAD

**Issue by hot007** [ACDguide/BigData#24]
Needs to be filled out and formatting made consistent with other pages (use of `code` font etc).

**Comment by hot007** [comment]
One thing that occurs to me is that we talk a lot about python libraries, and mention anaconda and miniconda (but not mamba, which is probably fine for now), but we don't explain what conda and pip (and thus venvs) are. Should that be added?
For people able to leverage hh5 it doesn't matter much, but for people managing their own environments it is invariably the greatest cause of pain with python...

**Comment by paigem** [comment]
Great point @hot007!

I wonder if it makes sense to have a dedicated page under the "Computations" heading for "Environments"? I don't think we mention the hh5 conda setup at all yet, so we could mention that and also provide some steps for users to create their own environments.
