### ISSUE TITLE
integrate pyAOS survey results in tools

### ISSUE THREAD

**Issue by paolap** [ACDguide/BigData#26]
We should have a look at this to reflect what packages the community use and how:

https://pyaos.github.io/census/

and

https://zenodo.org/record/5523491

for the actual results

**Comment by paigem** [comment]
I'm looking through the survey results now, and here is a list of packages used by survey responders that are not in our list in the JupyterBook. I don't think we necessarily need to include all of them here, but we should probably include many of the ones listed below.

Also, the packages from the survey a grouped according to their usage (e.g. core libraries, xarray extensions, etc.). Should we consider grouping packages along similar lines?

(I can add these to the book, but am holding off for now, as I don't know if any other updates have been made to the "Available tools" page in the meantime and don't want to duplicate work. @paolap or @AliciaTak let me know if you want me to add these now.)

### Used by at least 2 responders
- cmocean
- metpy 
- pyart
- gsw
- glidertools
- windspharm
- xhistogram
- xrft
- erddapy
- pydap
- shapely
- pyproj
- shapefile
- cftime
- cf_units
- nc_time_axis
- cfgrib
- pylab
- bokeh
- hvplot
- proplot
- sklearn
- intake
- statsmodels
- numba
- pyresample
- sparse
- skimage
- descartes
- Standard library packages:
   - pathlib, re, math, warnings, copy, time, pickle, shutil, argparse, collections, subprocess, urllib, gzip, logging, string, importlib, io, multiprocessing, itertools, fileinput, getopt, fnmatch, unittest, dataclasses, pdb, select, gc, calendar, uuid, socket, ctypes, tempfile
- Miscellaneous:
   - pytz, tqdm, psycopg2, dateutil, fsspec, sqalchemy, gcsfs, lxml, mpi4py, dash, joblib, rechunker

### Only used by one responder
- cdutil
- cdms2
- MV2

**Comment by DamienIrving** [comment]
I've written a bunch things about the PyAOS stack in the past (e.g. [stack summary](https://pyaos.github.io/stack/), [package index](https://pyaos.github.io/packages/), [census](https://pyaos.github.io/census/)) so I'd be happy to contribute to the book section about "identifying which languages/tools are best suited to specific tasks"

**Comment by paolap** [comment]
@paigem I'm back to work now so I will have a look at the list and see what to add, and yes we want to re-organise the packages based on function, it's partially done but not on the main branch if I remember well.
Of the ones listed as "standard" packages we might list only the ones like "calendar" that is useful to handle time axis etc but not stuff like "logging", "url lib", "string" for example as they are really generic packages. @DamienIrving I'll add you as reviewer when we pushed the changes, I'm hoping to work on this in the next few days

**Comment by paolap** [comment]
After having a better look I think this is the nearest to what we want to achieve:
 https://pyaos.github.io/packages/

Main differences are:

- while of course meteorology/oceanography packages are mostly relevant we're focusing on climate only
- We want to add a bit of introduction to each category highlighting what a package is most suited too. For example if you are working with UM data then you might be better off using iris. 
- Also, as we are looking at other programming languages too, not only python, the comparison might include that too.

**Comment by paigem** [comment]
Closing for now - added via recent PR
