### ISSUE TITLE
Add content to platforms page under "Accessing Data"

### ISSUE THREAD

**Issue by paigem** [ACDguide/BigData#36]
Add a page about the various platforms that can be used to work with (big) data in Australia.

These can include:
- NCI gadi
- NCI OOD
- CSIRO/BOM-specific?
- Pangeo Cloud

(Note: this can be done once https://github.com/ACDguide/BigData/issues/35 is completed)

**Comment by paigem** [comment]
#35 has been completed, so you are free to start adding content @hot007!

**Comment by hot007** [comment]
thanks! :)

**Comment by paigem** [comment]
Updates have been added via #37
