### ISSUE TITLE
Methods of data storage

### ISSUE THREAD

**Issue by hot007** [ACDguide/BigData#7]
@hot007 to create documentation around methods for large data storage.

- [x] background
- [x] CMS advice links
- [x] Zarr
- [x] nczarr (zarr as an optional back end from netcdf/4.8.0)

Create jupyterbook pages and open pull request when ready.

**Comment by hot007** [comment]
Okay I've populated this page at last to something approaching reasonable content. 
Additional contributions welcome please! I don't seem to be able to tag Dougie here.

**Comment by paigem** [comment]
@ScottWales are you able to add Dougie to this repo somehow? I don't seem to be able to add any new members.

**Comment by ScottWales** [comment]
Try now, I've made you an 'owner' of acdguide - https://github.com/orgs/ACDguide/people otherwise do you know his github name?

**Comment by paigem** [comment]
Thanks @ScottWales - I just invited him! Thanks for making me an "owner" - hope I don't make any big blunders with this new-found responsibility...

**Comment by hot007** [comment]
Ping @dougiesquire  for review, thanks :)

**Comment by hot007** [comment]
I'm wondering if this section should be expanded: https://acdguide.github.io/BigData/data_storage.html#advice-on-writing-large-datasets-efficiently
It's currently really just pointing to the CLEX wiki page (which is great), but maybe we should also explain chunking, compression and deflation here? Or is it better to just refer to the place with actual useful advice?

**Comment by dougiesquire** [comment]
Thanks @hot007!

> I'm wondering if this section should be expanded: https://acdguide.github.io/BigData/data_storage.html#advice-on-writing-large-datasets-efficiently
> It's currently really just pointing to the CLEX wiki page (which is great), but maybe we should also explain chunking, compression and deflation here? Or is it better to just refer to the place with actual useful advice?

I personally don't think it's necessary for us to re-explain anything that already has good/appropriate resources online. In fact, I think the best outcome is short sections that point at other great resources. If "all" the ACDguide does is to bring together a bunch of other resources/webpages into a single place, that would be a significant achievement that would benefit many.

IMO, that should be our goal. What are all those resources/webpages/tools we wished we knew about earlier? Let's get them in there!

**Comment by dougiesquire** [comment]
Also, I just learned GDAL includes some handy tools for working with zarr (including conversion - see https://gdal.org/drivers/raster/zarr.html#examples). Not sure where to include this right now, but just noting this here so we don't forget.

**Comment by hot007** [comment]
oh I considered mentioning GDAL but didn't. I'll do so. Also did you hear about the tentative support for zarr in Blender!? (a graphics engine). I'll leave that out for now!!

**Comment by hot007** [comment]
Closing this now, that page is done and ready for further review or release.
